app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('users/<int:pk>', views.users_detail, name='users_detail'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

photoservice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings          
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# MEDIA_ROOT を公開する(アクセス可能にする) 
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT) # 追加

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Category モデルを作成
class Category(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
       return self.title

class Photo(models.Model):
    title = models.CharField(max_length=150)
    comment = models.TextField(blank=True)
    image = models.ImageField(upload_to='photos')
    category = models.ForeignKey(Category, on_delete=models.PROTECT) # 追加 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from .models import Photo

def index(request):
    photos = Photo.objects.all().order_by('-created_at')
    return render(request, 'app/index.html', {'photos': photos})

def users_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    photos = user.photo_set.all().order_by('-created_at')
    return render(request, 'app/users_detail.html', {'user': user, 'photos': photos})

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>写真投稿サイト</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
		<header>
			<div class="container">
				<h1><a href="{% url 'app:index' %}">写真投稿サイト</a></h1>
				<div class="header-menu">
					<a href="">投稿</a> 
				</div>
	    </div>
		</header>
		<div class="container">
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %} 

{% block content %} 

<h2>トップページ</h2>

{% for photo in photos %}
	<img src="{{ photo.image.url }}" class="photo-img">
{% endfor %}

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
			<p>ユーザー名かパスワードが間違っています。</p> 
		{% endif %}
		<h2>ログイン</h2> 
		<label>ユーザー名</label>
		<input name="username">
		<br>
		<label>パスワード</label>
		<input type="password" name="password"> 
		<br>
		<input type="submit" value="ログイン">
</form>

{% endblock %}

app/templates/app/users_detail.html
{% extends 'app/base.html' %}

{% block content %}

<h2 class="user-name">@{{ user.username }}</h2>

{% for photo in photos %}
    <img src="{{ photo.image.url }}" class="photo-img">
{% endfor %}

{% endblock %}